### ISSUE TITLE
Ubuntu graphics repo?

### ISSUE THREAD

**Issue by 1iv3** [intel-gpu/kernel#7]
These packages are being held back for quite a while while using repositories.intel.com/graphics/ubuntu focal main

gedit gedit-common libva-drm2 libva-wayland2 libva-x11-2 libva2 va-driver-all xserver-xorg-core xserver-xorg-input-libinput xserver-xorg-video-amdgpu xserver-xorg-video-ati
xserver-xorg-video-fbdev xserver-xorg-video-intel xserver-xorg-video-nouveau xserver-xorg-video-qxl xserver-xorg-video-radeon xserver-xorg-video-vesa xserver-xorg-video-vmware

Just curious if there's a place I can read about updates and when things are pushed that would rock, thanks

**Comment by tripzero** [comment]
Does this help: https://dgpu-docs.intel.com/releases/index.html ?

**Comment by 1iv3** [comment]
ahh no I dont believe so, I beleive the packages are held back because they haven't been updated on the repository so I'm updating my apt and it shows held back packages from :
va-driver-all/focal 2.13.0+i643~u20.04 amd64 [upgradable from: 2.13.0-1]
va-driver-all/focal 2.13.0+i638~u20.04 amd64
va-driver-all/unstable,now 2.13.0-1 amd64 [installed,upgradable to: 2.13.0+i643~u20.04]
va-driver-all/focal 2.12.0+i620~u20.04 amd64
va-driver-all/focal 2.12.0+i611~u20.04 amd64
va-driver-all/focal 2.11.0+i593~u20.04 amd64
va-driver-all/focal 2.11.0+i592~u20.04 amd64
va-driver-all/focal 2.11.0+i571~u20.04 amd64

So actually I'm not sure, says upgreadable but when I do a full-upgrade to force the held packages my system becomes unbootable.. and it removes the nvidia-driver package that is also hosted on this repo
